
/* 3° Caso: Quais os 1000 clientes que mais compraram e quak é o primeiro e último nome deles o nome das cidades ? */

SELECT TOP(1000) DIMPRODUCT.PRODUCTNAME, FACTONLINESALES.SALESAMOUNT, DIMGEOGRAPHY.CITYNAME, DIMCUSTOMER.FIRSTNAME, DIMCUSTOMER.LASTNAME FROM DIMPRODUCT
INNER JOIN FACTONLINESALES
ON FACTONLINESALES.PRODUCTKEY = DIMPRODUCT.PRODUCTKEY
INNER JOIN DIMGEOGRAPHY
ON FACTONLINESALES.PRODUCTKEY = DIMGEOGRAPHY.GEOGRAPHYKEY
INNER JOIN DIMCUSTOMER
ON DIMCUSTOMER.GEOGRAPHYKEY = DIMGEOGRAPHY.GEOGRAPHYKEY
ORDER BY FACTONLINESALES.SALESAMOUNT DESC;